version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t webapplication1555 -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=$kastantin.knu@gmail.com --password=$ff077c3e-1354-4523-9feb-2af8d8647b94 registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$football-manager-2021/web
         docker push registry.heroku.com/$football-manager-2021/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $football-manager-2021